import React, { useState } from "react";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { DownloadIcon, Loader2Icon } from "lucide-react";

// 전체 프로젝트 소스 파일 목록
const allSourceFiles = [
  // 설정 파일
  "package.json",
  "tailwind.config.js",
  "tsconfig.json",
  "tsconfig.app.json",
  "tsconfig.node.json",
  "postcss.config.js",
  "vite.config.ts",
  "vercel.json",
  "index.html",
  "tailwind.css",

  // 메인 엔트리
  "src/App.tsx",
  "src/index.tsx",
  "src/breakpoints.ts",
  "src/lib/utils.ts",

  // 공통 컴포넌트
  "src/components/BackSubHeader.tsx",
  "src/components/DownloadButton.tsx",
  "src/components/PopupHeader.tsx",
  "src/components/common/ActionBar.tsx",
  "src/components/common/Keypad.tsx",

  // UI 컴포넌트
  "src/components/ui/alert.tsx",
  "src/components/ui/badge.tsx",
  "src/components/ui/button.tsx",
  "src/components/ui/card.tsx",
  "src/components/ui/checkbox.tsx",
  "src/components/ui/dialog.tsx",
  "src/components/ui/input.tsx",
  "src/components/ui/label.tsx",
  "src/components/ui/scroll-area.tsx",
  "src/components/ui/select.tsx",
  "src/components/ui/separator.tsx",
  "src/components/ui/switch.tsx",
  "src/components/ui/tabs.tsx",
  "src/components/ui/toggle-group.tsx",

  // 화면 컴포넌트
  "src/screens/Account/Account.tsx",
  "src/screens/Account/index.ts",
  "src/screens/AccountMain2/AccountMain2.tsx",
  "src/screens/AccountMain2/index.ts",
  "src/screens/AccountManagement/AccountManagement.tsx",
  "src/screens/AccountManagement/index.ts",
  "src/screens/AccountScreen/AccountScreen.tsx",
  "src/screens/AccountScreen/index.ts",
  "src/screens/AccountVerify/AccountVerify.tsx",
  "src/screens/AccountVerify/index.ts",
  "src/screens/AccountWrapper/AccountWrapper.tsx",
  "src/screens/AccountWrapper/index.ts",
  "src/screens/AddressDetailInput/AddressDetailInput.tsx",
  "src/screens/AddressDetailInput/index.ts",
  "src/screens/AddressDirectInput/AddressDirectInput.tsx",
  "src/screens/AddressDirectInput/index.ts",
  "src/screens/AddressInputMethod/AddressInputMethod.tsx",
  "src/screens/AddressInputMethod/index.ts",
  "src/screens/AddressPhotoConfirm/AddressPhotoConfirm.tsx",
  "src/screens/AddressPhotoConfirm/index.ts",
  "src/screens/AddressPhotoUpload/AddressPhotoUpload.tsx",
  "src/screens/AddressPhotoUpload/index.ts",
  "src/screens/AddressSearchApi/AddressSearchApi.tsx",
  "src/screens/AddressSearchApi/index.ts",
  "src/screens/AddressSearchResult/AddressSearchResult.tsx",
  "src/screens/AddressSearchResult/index.ts",
  "src/screens/ArsVerification/ArsVerification.tsx",
  "src/screens/ArsVerification/index.ts",
  "src/screens/AuthCodeInput/AuthCodeInput.tsx",
  "src/screens/AuthCodeInput/index.ts",
  "src/screens/AuthFailure/AuthFailure.tsx",
  "src/screens/AuthFailure/index.ts",
  "src/screens/AuthInfoInput/AuthInfoInput.tsx",
  "src/screens/AuthInfoInput/index.ts",
  "src/screens/AuthMethodSelect/AuthMethodSelect.tsx",
  "src/screens/AuthMethodSelect/index.ts",
  "src/screens/AutoWithdrawComplete/AutoWithdrawComplete.tsx",
  "src/screens/AutoWithdrawComplete/index.ts",
  "src/screens/AutoWithdrawConsent/AutoWithdrawConsent.tsx",
  "src/screens/AutoWithdrawConsent/index.ts",
  "src/screens/AutoWithdrawFailed/AutoWithdrawFailed.tsx",
  "src/screens/AutoWithdrawFailed/index.ts",
  "src/screens/CaptureTips/CaptureTips.tsx",
  "src/screens/CaptureTips/index.ts",
  "src/screens/CardVerification/CardVerification.tsx",
  "src/screens/CardVerification/index.ts",
  "src/screens/CarrierSelect/CarrierSelect.tsx",
  "src/screens/CarrierSelect/index.ts",
  "src/screens/CertificateConfirmKeyboard/CertificateConfirmKeyboard.tsx",
  "src/screens/CertificateConfirmKeyboard/index.ts",
  "src/screens/CertificateImportGuide/CertificateImportGuide.tsx",
  "src/screens/CertificateImportGuide/index.ts",
  "src/screens/CertificatePasswordKeyboard/CertificatePasswordKeyboard.tsx",
  "src/screens/CertificatePasswordKeyboard/index.ts",
  "src/screens/CertificateSelect/CertificateSelect.tsx",
  "src/screens/CertificateSelect/index.ts",
  "src/screens/CertificateSelectEmpty/CertificateSelectEmpty.tsx",
  "src/screens/CertificateSelectEmpty/index.ts",
  "src/screens/Common/Common.tsx",
  "src/screens/Common/index.ts",
  "src/screens/Common/sections/InputViewSection/InputViewSection.tsx",
  "src/screens/Common/sections/InputViewSection/index.ts",
  "src/screens/Common/sections/StatusBarSection/StatusBarSection.tsx",
  "src/screens/Common/sections/StatusBarSection/index.ts",
  "src/screens/Components/Components.tsx",
  "src/screens/CustomerInfoForm/CustomerInfoForm.tsx",
  "src/screens/CustomerInfoForm/index.ts",
  "src/screens/CustomerVerification/CustomerVerification.tsx",
  "src/screens/CustomerVerification/index.ts",
  "src/screens/DivWrapper/DivWrapper.tsx",
  "src/screens/DivWrapper/index.ts",
  "src/screens/Element/Element.tsx",
  "src/screens/Element/index.ts",
  "src/screens/ElementScreen/ElementScreen.tsx",
  "src/screens/ElementScreen/index.ts",
  "src/screens/ElementWrapper/ElementWrapper.tsx",
  "src/screens/ElementWrapper/index.ts",
  "src/screens/EmailInput/EmailInput.tsx",
  "src/screens/EmailInput/index.ts",
  "src/screens/Event/Event.tsx",
  "src/screens/Event/index.ts",
  "src/screens/EventEmpty/EventEmpty.tsx",
  "src/screens/EventEmpty/index.ts",
  "src/screens/EventScreen/EventScreen.tsx",
  "src/screens/EventScreen/index.ts",
  "src/screens/Favorite/Favorite.tsx",
  "src/screens/Favorite/index.ts",
  "src/screens/ForeignIdInput/ForeignIdInput.tsx",
  "src/screens/ForeignIdInput/index.ts",
  "src/screens/FundSourceSelection/FundSourceSelection.tsx",
  "src/screens/FundSourceSelection/index.ts",
  "src/screens/HistoryCancel/HistoryCancel.tsx",
  "src/screens/HistoryCancel/index.ts",
  "src/screens/HistoryComplete/HistoryComplete.tsx",
  "src/screens/HistoryComplete/index.ts",
  "src/screens/HistoryDetail1/HistoryDetail1.tsx",
  "src/screens/HistoryDetail1/index.ts",
  "src/screens/HistoryDetail2/HistoryDetail2.tsx",
  "src/screens/HistoryDetail2/index.ts",
  "src/screens/HistoryDetail3/HistoryDetail3.tsx",
  "src/screens/HistoryDetail3/index.ts",
  "src/screens/HistoryDetail4/HistoryDetail4.tsx",
  "src/screens/HistoryDetail4/index.ts",
  "src/screens/HistoryDetail5/HistoryDetail5.tsx",
  "src/screens/HistoryDetail5/index.ts",
  "src/screens/HistoryDetail6/HistoryDetail6.tsx",
  "src/screens/HistoryDetail6/index.ts",
  "src/screens/HistoryEmpty/HistoryEmpty.tsx",
  "src/screens/HistoryEmpty/index.ts",
  "src/screens/HistoryMain/HistoryMain.tsx",
  "src/screens/HistoryMain/index.ts",
  "src/screens/HistoryPeriodSelect/HistoryPeriodSelect.tsx",
  "src/screens/HistoryPeriodSelect/index.ts",
  "src/screens/HistoryProgress/HistoryProgress.tsx",
  "src/screens/HistoryProgress/index.ts",
  "src/screens/HistoryRefund/HistoryRefund.tsx",
  "src/screens/HistoryRefund/index.ts",
  "src/screens/Home/Home.tsx",
  "src/screens/Home/index.ts",
  "src/screens/Home/sections/CurrencySelectionSection/CurrencySelectionSection.tsx",
  "src/screens/Home/sections/CurrencySelectionSection/index.ts",
  "src/screens/Home/sections/TransferMethodSection/TransferMethodSection.tsx",
  "src/screens/Home/sections/TransferMethodSection/index.ts",
  "src/screens/HomeScreen/HomeScreen.tsx",
  "src/screens/HomeScreen/index.ts",
  "src/screens/HomeScreen/sections/AmountInputSection/AmountInputSection.tsx",
  "src/screens/HomeScreen/sections/AmountInputSection/index.ts",
  "src/screens/HomeScreen/sections/ExchangeRateSection/ExchangeRateSection.tsx",
  "src/screens/HomeScreen/sections/ExchangeRateSection/index.ts",
  "src/screens/HomeWrapper/HomeWrapper.tsx",
  "src/screens/HomeWrapper/index.ts",
  "src/screens/HomeWrapper/sections/BankDetailsSection/BankDetailsSection.tsx",
  "src/screens/HomeWrapper/sections/BankDetailsSection/index.ts",
  "src/screens/HomeWrapper/sections/CurrencyExchangeSection/CurrencyExchangeSection.tsx",
  "src/screens/HomeWrapper/sections/CurrencyExchangeSection/index.ts",
  "src/screens/IdFrontCapture/IdFrontCapture.tsx",
  "src/screens/IdFrontCapture/index.ts",
  "src/screens/IdRegistrationMethod/IdRegistrationMethod.tsx",
  "src/screens/IdRegistrationMethod/index.ts",
  "src/screens/IdTypeSelection/IdTypeSelection.tsx",
  "src/screens/IdTypeSelection/index.ts",
  "src/screens/Login/Login.tsx",
  "src/screens/Login/index.ts",
  "src/screens/LoginScreen/LoginScreen.tsx",
  "src/screens/LoginScreen/index.ts",
  "src/screens/Mypage/Mypage.tsx",
  "src/screens/Mypage/index.ts",
  "src/screens/Mypage/sections/ActionButtonSection/ActionButtonSection.tsx",
  "src/screens/Mypage/sections/ActionButtonSection/index.ts",
  "src/screens/Mypage/sections/DivSubsection/DivSubsection.tsx",
  "src/screens/Mypage/sections/DivSubsection/index.ts",
  "src/screens/Mypage/sections/DivWrapperSubsection/DivWrapperSubsection.tsx",
  "src/screens/Mypage/sections/DivWrapperSubsection/index.ts",
  "src/screens/Mypage/sections/FrameSubsection/FrameSubsection.tsx",
  "src/screens/Mypage/sections/FrameSubsection/index.ts",
  "src/screens/Mypage/sections/LoginSection/LoginSection.tsx",
  "src/screens/Mypage/sections/LoginSection/index.ts",
  "src/screens/Mypage/sections/MainContentSection/MainContentSection.tsx",
  "src/screens/Mypage/sections/MainContentSection/index.ts",
  "src/screens/Mypage/sections/ReferralInfoSection/ReferralInfoSection.tsx",
  "src/screens/Mypage/sections/ReferralInfoSection/index.ts",
  "src/screens/Mypage/sections/StatusBarSection/StatusBarSection.tsx",
  "src/screens/Mypage/sections/StatusBarSection/index.ts",
  "src/screens/Mypage/sections/TopSubsection/TopSubsection.tsx",
  "src/screens/Mypage/sections/TopSubsection/index.ts",
  "src/screens/Mypage/sections/TransactionSummarySection/TransactionSummarySection.tsx",
  "src/screens/Mypage/sections/TransactionSummarySection/index.ts",
  "src/screens/Mypage/sections/UiStatusBarWrapperSubsection/UiStatusBarWrapperSubsection.tsx",
  "src/screens/Mypage/sections/UiStatusBarWrapperSubsection/index.ts",
  "src/screens/Mypage/sections/UserInfoSection/UserInfoSection.tsx",
  "src/screens/Mypage/sections/UserInfoSection/index.ts",
  "src/screens/Mypage/sections/ViewWrapperSubsection/ViewWrapperSubsection.tsx",
  "src/screens/Mypage/sections/ViewWrapperSubsection/index.ts",
  "src/screens/Mypage/sections/WalletSection/WalletSection.tsx",
  "src/screens/Mypage/sections/WalletSection/index.ts",
  "src/screens/MypageBs/MypageBs.tsx",
  "src/screens/MypageBs/index.ts",
  "src/screens/MypagePopup/MypagePopup.tsx",
  "src/screens/MypagePopup/index.ts",
  "src/screens/MypageScreen/MypageScreen.tsx",
  "src/screens/MypageScreen/index.ts",
  "src/screens/MypageScreen/sections/ContentsWrapperSubsection/ContentsWrapperSubsection.tsx",
  "src/screens/MypageScreen/sections/ContentsWrapperSubsection/index.ts",
  "src/screens/MypageScreen/sections/UiStatusBarWrapperSubsection/UiStatusBarWrapperSubsection.tsx",
  "src/screens/MypageScreen/sections/UiStatusBarWrapperSubsection/index.ts",
  "src/screens/MypageWrapper/MypageWrapper.tsx",
  "src/screens/MypageWrapper/index.ts",
  "src/screens/MypageWrapper/sections/UiStatusBarSubsection/UiStatusBarSubsection.tsx",
  "src/screens/MypageWrapper/sections/UiStatusBarSubsection/index.ts",
  "src/screens/MypageWrapper/sections/ViewSubsection/ViewSubsection.tsx",
  "src/screens/MypageWrapper/sections/ViewSubsection/index.ts",
  "src/screens/Nationality/Nationality.tsx",
  "src/screens/Nationality/index.ts",
  "src/screens/NewAccountPassword/NewAccountPassword.tsx",
  "src/screens/NewAccountPassword/index.ts",
  "src/screens/NewAccountPasswordFilled/NewAccountPasswordFilled.tsx",
  "src/screens/NewAccountPasswordFilled/index.ts",
  "src/screens/NewAccountPasswordWechat/NewAccountPasswordWechat.tsx",
  "src/screens/NewAccountPasswordWechat/index.ts",
  "src/screens/NewAccountPhoneInput/NewAccountPhoneInput.tsx",
  "src/screens/NewAccountPhoneInput/index.ts",
  "src/screens/NewAccountReferral/NewAccountReferral.tsx",
  "src/screens/NewAccountReferral/index.ts",
  "src/screens/OccupationSelection/OccupationSelection.tsx",
  "src/screens/OccupationSelection/index.ts",
  "src/screens/OverseasRemitConfirm/OverseasRemitConfirm.tsx",
  "src/screens/OverseasRemitConfirm/index.ts",
  "src/screens/OverseasRemitConfirm/sections/StatusBarSection/StatusBarSection.tsx",
  "src/screens/OverseasRemitConfirm/sections/StatusBarSection/index.ts",
  "src/screens/OverseasRemitConfirm/sections/TransactionDetailsSection/TransactionDetailsSection.tsx",
  "src/screens/OverseasRemitConfirm/sections/TransactionDetailsSection/index.ts",
  "src/screens/OverseasRemitConfirm/sections/UserInformationSection/UserInformationSection.tsx",
  "src/screens/OverseasRemitConfirm/sections/UserInformationSection/index.ts",
  "src/screens/OverseasRemitContacts/OverseasRemitContacts.tsx",
  "src/screens/OverseasRemitContacts/index.ts",
  "src/screens/OverseasRemitContacts/sections/ActionButtonsSection/ActionButtonsSection.tsx",
  "src/screens/OverseasRemitContacts/sections/ActionButtonsSection/index.ts",
  "src/screens/OverseasRemitContacts/sections/ContactListSection/ContactListSection.tsx",
  "src/screens/OverseasRemitContacts/sections/ContactListSection/index.ts",
  "src/screens/OverseasRemitCoupon/OverseasRemitCoupon.tsx",
  "src/screens/OverseasRemitCoupon/index.ts",
  "src/screens/OverseasRemitCoupon/sections/CouponDetailsSection/CouponDetailsSection.tsx",
  "src/screens/OverseasRemitCoupon/sections/CouponDetailsSection/index.ts",
  "src/screens/OverseasRemitCoupon/sections/CouponListSection/CouponListSection.tsx",
  "src/screens/OverseasRemitCoupon/sections/CouponListSection/index.ts",
  "src/screens/OverseasRemitFail/OverseasRemitFail.tsx",
  "src/screens/OverseasRemitFail/index.ts",
  "src/screens/OverseasRemitHistory/OverseasRemitHistory.tsx",
  "src/screens/OverseasRemitHistory/index.ts",
  "src/screens/OverseasRemitIdInput/OverseasRemitIdInput.tsx",
  "src/screens/OverseasRemitIdInput/index.ts",
  "src/screens/OverseasRemitNickname/OverseasRemitNickname.tsx",
  "src/screens/OverseasRemitNickname/index.ts",
  "src/screens/OverseasRemitNickname/sections/DisplaySection/DisplaySection.tsx",
  "src/screens/OverseasRemitNickname/sections/DisplaySection/index.ts",
  "src/screens/OverseasRemitNickname/sections/MainContentSection/MainContentSection.tsx",
  "src/screens/OverseasRemitNickname/sections/MainContentSection/index.ts",
  "src/screens/OverseasRemitPaymentConfirm/OverseasRemitPaymentConfirm.tsx",
  "src/screens/OverseasRemitPaymentConfirm/index.ts",
  "src/screens/OverseasRemitPaymentConfirm/sections/PaymentInformationSection/PaymentInformationSection.tsx",
  "src/screens/OverseasRemitPaymentConfirm/sections/PaymentInformationSection/index.ts",
  "src/screens/OverseasRemitPaymentConfirm/sections/StatusBarSection/StatusBarSection.tsx",
  "src/screens/OverseasRemitPaymentConfirm/sections/StatusBarSection/index.ts",
  "src/screens/OverseasRemitPaymentConfirm/sections/TransactionDetailsSection/TransactionDetailsSection.tsx",
  "src/screens/OverseasRemitPaymentConfirm/sections/TransactionDetailsSection/index.ts",
  "src/screens/OverseasRemitPin/OverseasRemitPin.tsx",
  "src/screens/OverseasRemitPin/index.ts",
  "src/screens/OverseasRemitReceiverInfo/OverseasRemitReceiverInfo.tsx",
  "src/screens/OverseasRemitReceiverInfo/index.ts",
  "src/screens/OverseasRemitRecipient/OverseasRemitRecipient.tsx",
  "src/screens/OverseasRemitRecipient/index.ts",
  "src/screens/OverseasRemitRecipient/sections/AdditionalNotesSection/AdditionalNotesSection.tsx",
  "src/screens/OverseasRemitRecipient/sections/AdditionalNotesSection/index.ts",
  "src/screens/OverseasRemitRecipient/sections/PaymentMethodSection/PaymentMethodSection.tsx",
  "src/screens/OverseasRemitRecipient/sections/PaymentMethodSection/index.ts",
  "src/screens/OverseasRemitRecipient/sections/ReceiveCountrySection/ReceiveCountrySection.tsx",
  "src/screens/OverseasRemitRecipient/sections/ReceiveCountrySection/index.ts",
  "src/screens/OverseasRemitRecipient/sections/SenderInformationSection/SenderInformationSection.tsx",
  "src/screens/OverseasRemitRecipient/sections/SenderInformationSection/index.ts",
  "src/screens/OverseasRemitTransferInfo/OverseasRemitTransferInfo.tsx",
  "src/screens/OverseasRemitTransferInfo/index.ts",
  "src/screens/OverseasRemitTransferInfo/sections/AccountDetailsSection/AccountDetailsSection.tsx",
  "src/screens/OverseasRemitTransferInfo/sections/AccountDetailsSection/index.ts",
  "src/screens/OverseasRemitTransferInfo/sections/CurrencySelectionSection/CurrencySelectionSection.tsx",
  "src/screens/OverseasRemitTransferInfo/sections/CurrencySelectionSection/index.ts",
  "src/screens/OverseasRemitTransferInfo/sections/TransferInformationSection/TransferInformationSection.tsx",
  "src/screens/OverseasRemitTransferInfo/sections/TransferInformationSection/index.ts",
  "src/screens/Overseasremit/Overseasremit.tsx",
  "src/screens/Overseasremit/index.ts",
  "src/screens/OverseasremitScreen/OverseasremitScreen.tsx",
  "src/screens/OverseasremitScreen/index.ts",
  "src/screens/OverseasremitWrapper/OverseasremitWrapper.tsx",
  "src/screens/OverseasremitWrapper/index.ts",
  "src/screens/PassportInfoInput/PassportInfoInput.tsx",
  "src/screens/PassportInfoInput/index.ts",
  "src/screens/PasswordInputKeypad/PasswordInputKeypad.tsx",
  "src/screens/PasswordInputKeypad/index.ts",
  "src/screens/PasswordReset/PasswordReset.tsx",
  "src/screens/PasswordReset/index.ts",
  "src/screens/PhotoConfirmDialog/PhotoConfirmDialog.tsx",
  "src/screens/PhotoConfirmDialog/index.ts",
  "src/screens/PhotoConfirmation/PhotoConfirmation.tsx",
  "src/screens/PhotoConfirmation/index.ts",
  "src/screens/PinConfirm/PinConfirm.tsx",
  "src/screens/PinConfirm/index.ts",
  "src/screens/PinEntry/PinEntry.tsx",
  "src/screens/PinEntry/index.ts",
  "src/screens/PinInput/PinInput.tsx",
  "src/screens/PinInput/index.ts",
  "src/screens/PinPin/PinPin.tsx",
  "src/screens/PinPin/index.ts",
  "src/screens/PinPinScreen/PinPinScreen.tsx",
  "src/screens/PinPinScreen/index.ts",
  "src/screens/PublishingStatus/PublishingStatus.tsx",
  "src/screens/PublishingStatus/index.ts",
  "src/screens/ReferralCodeInput/ReferralCodeInput.tsx",
  "src/screens/ReferralCodeInput/index.ts",
  "src/screens/Screen/Screen.tsx",
  "src/screens/Screen/index.ts",
  "src/screens/Screen4/Screen4.tsx",
  "src/screens/Screen4/index.ts",
  "src/screens/Screen5/Screen5.tsx",
  "src/screens/Screen5/index.ts",
  "src/screens/Screen6/Screen6.tsx",
  "src/screens/Screen6/index.ts",
  "src/screens/Screen7/Screen7.tsx",
  "src/screens/Screen7/index.ts",
  "src/screens/Screen7/sections/DivWrapperSubsection/DivWrapperSubsection.tsx",
  "src/screens/Screen7/sections/DivWrapperSubsection/index.ts",
  "src/screens/Screen7/sections/FrameSubsection/FrameSubsection.tsx",
  "src/screens/Screen7/sections/FrameSubsection/index.ts",
  "src/screens/Screen7/sections/FrameWrapperSubsection/FrameWrapperSubsection.tsx",
  "src/screens/Screen7/sections/FrameWrapperSubsection/index.ts",
  "src/screens/Screen7/sections/GiftCardSection/GiftCardSection.tsx",
  "src/screens/Screen7/sections/GiftCardSection/index.ts",
  "src/screens/Screen7/sections/MainContentSection/MainContentSection.tsx",
  "src/screens/Screen7/sections/MainContentSection/index.ts",
  "src/screens/Screen7/sections/QRCodeSection/QRCodeSection.tsx",
  "src/screens/Screen7/sections/QRCodeSection/index.ts",
  "src/screens/Screen7/sections/StatusBarSection/StatusBarSection.tsx",
  "src/screens/Screen7/sections/StatusBarSection/index.ts",
  "src/screens/Screen7/sections/UiStatusBarSubsection/UiStatusBarSubsection.tsx",
  "src/screens/Screen7/sections/UiStatusBarSubsection/index.ts",
  "src/screens/Screen7/sections/ViewSubsection/ViewSubsection.tsx",
  "src/screens/Screen7/sections/ViewSubsection/index.ts",
  "src/screens/Screen7/sections/WalletSection/WalletSection.tsx",
  "src/screens/Screen7/sections/WalletSection/index.ts",
  "src/screens/Screen8/Screen8.tsx",
  "src/screens/Screen8/index.ts",
  "src/screens/Screen8/sections/CurrencySelectionSection/CurrencySelectionSection.tsx",
  "src/screens/Screen8/sections/CurrencySelectionSection/index.ts",
  "src/screens/Screen8/sections/TransactionDetailsSection/TransactionDetailsSection.tsx",
  "src/screens/Screen8/sections/TransactionDetailsSection/index.ts",
  "src/screens/SelfCheckAuth/SelfCheckAuth.tsx",
  "src/screens/SelfCheckAuth/index.ts",
  "src/screens/SelfieCapture/SelfieCapture.tsx",
  "src/screens/SelfieCapture/index.ts",
  "src/screens/SelfieCaptureCountdown/SelfieCaptureCountdown.tsx",
  "src/screens/SelfieCaptureCountdown/index.ts",
  "src/screens/SelfieVerification/SelfieVerification.tsx",
  "src/screens/SelfieVerification/index.ts",
  "src/screens/SelfieVerificationProgress/SelfieVerificationProgress.tsx",
  "src/screens/SelfieVerificationProgress/index.ts",
  "src/screens/ServiceCertificate/ServiceCertificate.tsx",
  "src/screens/ServiceCertificate/index.ts",
  "src/screens/ServiceTerms/ServiceTerms.tsx",
  "src/screens/ServiceTerms/index.ts",
  "src/screens/Servicecert/Servicecert.tsx",
  "src/screens/Servicecert/index.ts",
  "src/screens/ServicecertScreen/ServicecertScreen.tsx",
  "src/screens/ServicecertScreen/index.ts",
  "src/screens/ServicecertWrapper/ServicecertWrapper.tsx",
  "src/screens/ServicecertWrapper/index.ts",
  "src/screens/Settings/Settings.tsx",
  "src/screens/Settings/index.ts",
  "src/screens/SettingsScreen/SettingsScreen.tsx",
  "src/screens/SettingsScreen/index.ts",
  "src/screens/SettingsWrapper/SettingsWrapper.tsx",
  "src/screens/SettingsWrapper/index.ts",
  "src/screens/SignupComplete/SignupComplete.tsx",
  "src/screens/SignupComplete/index.ts",
  "src/screens/SignupTerms/SignupTerms.tsx",
  "src/screens/SignupTerms/index.ts",
  "src/screens/SmsVerification/SmsVerification.tsx",
  "src/screens/SmsVerification/index.ts",
  "src/screens/SplashScreen/SplashScreen.tsx",
  "src/screens/SplashScreen/index.ts",
  "src/screens/StampGuide/StampGuide.tsx",
  "src/screens/StampGuide/index.ts",
  "src/screens/TermsScreen/TermsScreen.tsx",
  "src/screens/TermsScreen/index.ts",
  "src/screens/Transform/Transform.tsx",
  "src/screens/Transform/index.ts",
  "src/screens/Transform/sections/ContainerSubsection/ContainerSubsection.tsx",
  "src/screens/Transform/sections/ContainerSubsection/index.ts",
  "src/screens/Transform/sections/FrameSubsection/FrameSubsection.tsx",
  "src/screens/Transform/sections/FrameSubsection/index.ts",
  "src/screens/TransferComplete/TransferComplete.tsx",
  "src/screens/TransferComplete/index.ts",
  "src/screens/TransferConfirm/TransferConfirm.tsx",
  "src/screens/TransferConfirm/index.ts",
  "src/screens/TransferFailed/TransferFailed.tsx",
  "src/screens/TransferFailed/index.ts",
  "src/screens/TransferHistory/TransferHistory.tsx",
  "src/screens/TransferHistory/index.ts",
  "src/screens/TransferInput/TransferInput.tsx",
  "src/screens/TransferInput/index.ts",
  "src/screens/TransferMethod/TransferMethod.tsx",
  "src/screens/TransferMethod/index.ts",
  "src/screens/TransferReceipt/TransferReceipt.tsx",
  "src/screens/TransferReceipt/index.ts",
  "src/screens/TransferScreen/TransferScreen.tsx",
  "src/screens/TransferScreen/index.ts",
  "src/screens/UnregisteredAccount/UnregisteredAccount.tsx",
  "src/screens/UnregisteredAccount/index.ts",
  "src/screens/UserAgreement/UserAgreement.tsx",
  "src/screens/UserAgreement/index.ts",
  "src/screens/UserInfoScreen/UserInfoScreen.tsx",
  "src/screens/UserInfoScreen/index.ts",
  "src/screens/VerificationFailed/VerificationFailed.tsx",
  "src/screens/VerificationFailed/index.ts",
  "src/screens/VerificationProgress/VerificationProgress.tsx",
  "src/screens/VerificationProgress/index.ts",
  "src/screens/VerificationSuccess/VerificationSuccess.tsx",
  "src/screens/VerificationSuccess/index.ts",
  "src/screens/WalletCharge/WalletCharge.tsx",
  "src/screens/WalletCharge/index.ts",
  "src/screens/WalletChargeComplete/WalletChargeComplete.tsx",
  "src/screens/WalletChargeComplete/index.ts",
  "src/screens/WalletScreen/WalletScreen.tsx",
  "src/screens/WalletScreen/index.ts",
  "src/screens/WalletWithdraw/WalletWithdraw.tsx",
  "src/screens/WalletWithdraw/index.ts",
  "src/screens/WalletWithdrawComplete/WalletWithdrawComplete.tsx",
  "src/screens/WalletWithdrawComplete/index.ts",
  "src/screens/WithdrawComplete/WithdrawComplete.tsx",
  "src/screens/WithdrawComplete/index.ts",
];

// 전체 소스 다운로드 버튼
export const DownloadAllButton: React.FC = () => {
  const [isDownloading, setIsDownloading] = useState(false);
  const [progress, setProgress] = useState(0);

  const handleDownloadAll = async () => {
    setIsDownloading(true);
    setProgress(0);

    try {
      const zip = new JSZip();
      const totalFiles = allSourceFiles.length;
      let processedFiles = 0;

      for (const filePath of allSourceFiles) {
        try {
          const response = await fetch(`/api/source/${encodeURIComponent(filePath)}`);

          if (response.ok) {
            const content = await response.text();
            zip.file(filePath, content);
          } else {
            console.warn(`파일을 가져올 수 없습니다: ${filePath}`);
          }
        } catch (error) {
          console.warn(`파일 처리 중 오류: ${filePath}`, error);
        }

        processedFiles++;
        setProgress(Math.round((processedFiles / totalFiles) * 100));
      }

      // ZIP 파일 생성 및 다운로드
      const timestamp = new Date().toISOString().slice(0, 10).replace(/-/g, "");
      const zipBlob = await zip.generateAsync({ type: "blob" });
      saveAs(zipBlob, `hanpass_all_source_${timestamp}.zip`);
    } catch (error) {
      console.error("다운로드 중 오류:", error);
      alert("전체 소스 다운로드 중 오류가 발생했습니다.");
    } finally {
      setIsDownloading(false);
      setProgress(0);
    }
  };

  return (
    <button
      onClick={handleDownloadAll}
      disabled={isDownloading}
      className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
        isDownloading
          ? "bg-gray-100 text-gray-400 cursor-not-allowed"
          : "bg-green-600 text-white hover:bg-green-700"
      }`}
      title="전체 소스 다운로드"
    >
      {isDownloading ? (
        <>
          <Loader2Icon className="w-4 h-4 animate-spin" />
          다운로드 중... {progress}%
        </>
      ) : (
        <>
          <DownloadIcon className="w-4 h-4" />
          전체 소스 다운로드
        </>
      )}
    </button>
  );
};
